### ISSUE TITLE
Add a "None" binding

### ISSUE THREAD

**Issue by cheatfreak47** [sewer56lol/Heroes-Controller-Hook#1]
It would be nice if the mod could process not binding some controls at all.
I'd like to set CameraLeft and CameraRight to none, so that just the triggers handle it, then bind RB to Team Blast.

**Comment by Sewer56** [comment]
I'll implement it when I'm done with assignments ;>); even though it's a 5 minute code edit most likely.

**Comment by Sewer56** [comment]
Implemented as of 49e363f183956f0327f007e59fabdc021c71f63d .
